name: Deploy Memory Tracker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to production server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        script: |
          cd /root/memory_tracker
          git pull origin main
          docker compose down
          docker compose up -d --build
